PWD=$(pwd)

VIM_CONFIG=".vimrc"
TMUX_CONFIG=".tmux.conf"
WEZTERM_CONFIG=".wezterm.lua"
NVIM_CONFIG="init.lua"
STARSHIP_CONFIG="starship.toml"

VIM_CONFIG_FILE_SRC="${PWD}/${VIM_CONFIG}"
TMUX_CONFIG_FILE_SRC="${PWD}/${TMUX_CONFIG}"
WEZTERM_CONFIG_FILE_SRC="${PWD}/${WEZTERM_CONFIG}"
NVIM_CONFIG_FILE_SRC="${PWD}/${NVIM_CONFIG}"
STARSHIP_CONFIG_FILE_SRC="${PWD}/${STARSHIP_CONFIG}"

VIM_CONFIG_FILE_DEST="$HOME/$VIM_CONFIG"
TMUX_CONFIG_FILE_DEST="$HOME/$TMUX_CONFIG"
WEZTERM_CONFIG_FILE_DEST="$HOME/$WEZTERM_CONFIG"
NVIM_CONFIG_PATH_DEST="$HOME/.config/nvim"
NVIM_CONFIG_FILE_DEST="$NVIM_CONFIG_PATH_DEST/$NVIM_CONFIG"
STARSHIP_CONFIG_PATH_DEST="$HOME/.config"
STARSHIP_CONFIG_FILE_DEST="$STARSHIP_CONFIG_PATH_DEST/$STARSHIP_CONFIG"

rm -f "$VIM_CONFIG_FILE_DEST"
rm -f "$TMUX_CONFIG_FILE_DEST"
rm -f "$WEZTERM_CONFIG_FILE_DEST"
rm -f "$NVIM_CONFIG_FILE_DEST"
rm -f "$STARSHIP_CONFIG_FILE_DEST"

ln -s "$VIM_CONFIG_FILE_SRC" "$VIM_CONFIG_FILE_DEST"
ln -s "$TMUX_CONFIG_FILE_SRC" "$TMUX_CONFIG_FILE_DEST"
ln -s "$WEZTERM_CONFIG_FILE_SRC" "$WEZTERM_CONFIG_FILE_DEST"
mkdir -p "$NVIM_CONFIG_PATH_DEST"
ln -s "$NVIM_CONFIG_FILE_SRC" "$NVIM_CONFIG_FILE_DEST"
mkdir -p "$STARSHIP_CONFIG_PATH_DEST"
ln -s "$STARSHIP_CONFIG_FILE_SRC" "$STARSHIP_CONFIG_FILE_DEST"

git config --global alias.tree 'log --all --decorate --graph --oneline'
git config --global alias.tree-full 'log --all --decorate --graph'
git config --global alias.show-files 'show --name-status --oneline'

tmux source "$HOME/$TMUX_CONFIG"

